### ISSUE TITLE
Invalid record passed to recordMetadata

### ISSUE THREAD

**Issue by DBinaghi** [GerZah/plugin-ReassignFiles#1]
Hi.
Just installed your plugin, config page was ok, but when I click on Reassign Files I get the following error:

```
InvalidArgumentException: Invalid record passed to recordMetadata. in /home/wearewaa/public_html/application/views/helpers/Metadata.php:58
Stack trace:
#0 /home/wearewaa/public_html/application/libraries/Zend/View/Abstract.php(349): Omeka_View_Helper_Metadata->metadata(NULL, Array, Array)
#1 /home/wearewaa/public_html/application/libraries/globals.php(2042): Zend_View_Abstract->__call('metadata', Array)
#2 /home/wearewaa/public_html/plugins/ReassignFiles/ReassignFilesPlugin.php(164): metadata(NULL, Array)
#3 /home/wearewaa/public_html/plugins/ReassignFiles/controllers/IndexController.php(17): ReassignFilesPlugin::reassignFiles_getFileNames()
#4 /home/wearewaa/public_html/application/libraries/Zend/Controller/Action.php(516): ReassignFiles_IndexController->indexAction()
#5 /home/wearewaa/public_html/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#6 /home/wearewaa/public_html/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#7 /home/wearewaa/public_html/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#8 /home/wearewaa/public_html/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#9 /home/wearewaa/public_html/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#10 /home/wearewaa/public_html/admin/index.php(28): Omeka_Application->run()
#11 {main}
```

**Comment by DBinaghi** [comment]
Hi again. 

I've found a solution, although I am not sure what is causing the problem (it might be another plugin, maybe **Admin Images**).
Basically, the select in `reassignFiles_getFileNames` retrieves also a `$itemId = 0, and following $itemNames[$itemId] = metadata($item, array('Dublin Core', 'Title'));` fails.

Solution:
replace
`$itemNames[$itemId] = metadata($item, array('Dublin Core', 'Title'));`
with 
```
if (isset($item)) {
	$itemNames[$itemId] = metadata($item, array('Dublin Core', 'Title'));
}
```

Hope this helps.

**Comment by GerZah** [comment]
Hi. I'm terribly sorry, but I am no longer working on this project. This plugin was work-related back then, but I've since switched jobs, so I am not even using Omeka anymore … let alone develop / maintain Omeka plugins. So unfortunately, there's no way that I could even look into what seems to be the problem, let alone provide a solution. — Sorry! :-(

**Comment by DBinaghi** [comment]
Hello. Thanks for your reply. I perfectly understand the situation.
Hope you don't mind then if I fork it and prepare a release, attributing rights to you of course: I think this plugin could be very handy for some other users.

**Comment by GerZah** [comment]
That's perfectly fine – it's open source, so do whatever you want to do with it. 👍
